### ISSUE TITLE
The overflowing RenderFlex has an orientation of Axis.horizontal

### ISSUE THREAD

**Issue by sivatharan** [biessek/flutter_country_picker#9]
when we are try to put in side the TextFormField
![phone flutter](https://user-images.githubusercontent.com/9088637/57012346-9fabc380-6c23-11e9-979a-b5ba3e369055.png)

              TextFormField(
                obscureText: true,
                controller: _passwordCtrl,
                onSaved: (String value) {
                  _phone= value;
                },
            
                validator: (value) =>
                    value.isEmpty ? 'phone can\'t be empty' : null,
                decoration: _themePage.textBoxDecorationForPhoneNumber(
                  
                    IconButton(
                      iconSize: 32.0,
                        icon: CountryPicker(
                      showDialingCode: true,
                      showName: false,
                      showFlag: true,
                      onChanged: (Country country) {
                        setState(() {
                          _selected = country;
                        });
                      },
                      selectedCountry: _selected,
                    ),
                        onPressed: () {
                        }),
                    "Phone"),
              ),

**Comment by biessek** [comment]
I couldn't check effectivelly because I don't have the implementation of `textBoxDecorationForPhoneNumber`...

I think this is related to the limited size in the parent widget:  
`IconButton(iconSize: 32.0,`

The `prefix` property is most suitable for this case instead of `prefixIcon`.
Also, you don't need this IconButton... You can use something like `prefix: CountryPicker(...)` directly:
